### ISSUE TITLE
env

### ISSUE THREAD

**Issue by zhengduoru** [Wizaron/instance-segmentation-pytorch#1]
I only found "instance-segmentation-pytorch/code/conda_environment.yml"
but there is not "instance-segmentation-pytorch/code/pytorch/conda_environment.yml"
is this a mistake ?

**Comment by Wizaron** [comment]
The path of environment file in README.md is wrong. I updated README such that

"instance-segmentation-pytorch/code/pytorch/conda_environment.yml" -> "instance-segmentation-pytorch/code/conda_environment.yml"
