### ISSUE TITLE
ConnectionError 

### ISSUE THREAD

**Issue by zhengduoru** [Wizaron/instance-segmentation-pytorch#3]
when i run 
`python train.py --usegpu  --nepochs 10 --batchsize 1 --nworkers 1`
I got the error below. I am in China. I wonder if there is the  internet block. And what should I do?

Architecture(
  (cnn): BaseCNN(
    (model): ModifiedVGG(
      (model): Sequential(
        (0): Conv2d (3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (1): ReLU(inplace)
        (2): Conv2d (64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (3): ReLU(inplace)
        (4): MaxPool2d(kernel_size=(2, 2), stride=(2, 2), dilation=(1, 1))
        (5): Conv2d (64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (6): ReLU(inplace)
        (7): Conv2d (128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (8): ReLU(inplace)
        (9): MaxPool2d(kernel_size=(2, 2), stride=(2, 2), dilation=(1, 1))
        (10): Conv2d (128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (11): ReLU(inplace)
        (12): Conv2d (256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (13): ReLU(inplace)
        (14): Conv2d (256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (15): ReLU(inplace)
      )
    )
  )
  (renet1): ReNet(
    (rnn_hor): GRU(256, 100, batch_first=True, bidirectional=True)
    (rnn_ver): GRU(200, 100, batch_first=True, bidirectional=True)
  )
  (renet2): ReNet(
    (rnn_hor): GRU(200, 100, batch_first=True, bidirectional=True)
    (rnn_ver): GRU(200, 100, batch_first=True, bidirectional=True)
  )
  (upsampling1): ConvTranspose2d (200, 100, kernel_size=(2, 2), stride=(2, 2))
  (relu1): ReLU()
  (upsampling2): ConvTranspose2d (228, 100, kernel_size=(2, 2), stride=(2, 2))
  (relu2): ReLU()
  (fg_seg_output): Conv2d (164, 2, kernel_size=(1, 1), stride=(1, 1))
  (ins_seg_output): Conv2d (164, 16, kernel_size=(1, 1), stride=(1, 1))
  (ins_cls_cnn): Sequential(
    (pool1): MaxPool2d(kernel_size=(2, 2), stride=(2, 2), dilation=(1, 1))
    (conv1): Conv2d (200, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu1): ReLU()
    (conv2): Conv2d (64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu2): ReLU()
    (pool2): MaxPool2d(kernel_size=(2, 2), stride=(2, 2), dilation=(1, 1))
    (conv3): Conv2d (64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu3): ReLU()
    (conv4): Conv2d (64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu4): ReLU()
    (pool3): AdaptiveAvgPool2d(output_size=(1, 1))
  )
  (ins_cls_out): Sequential(
    (linear): Linear(in_features=64, out_features=1)
    (sigmoid): Sigmoid()
  )
)
Testing:     [METRIC] CE Cost : 0.902625203133 | MSE Cost : 0.118421502411 | Discriminative Cost : 7.28294658661 | Dice Cost : 0.835230827332 |
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/duoduo/anaconda3/envs/ins-seg-pytorch/lib/python2.7/site-packages/visdom/__init__.py", line 261, in _send
    data=json.dumps(msg),
  File "/home/duoduo/anaconda3/envs/ins-seg-pytorch/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/duoduo/anaconda3/envs/ins-seg-pytorch/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/duoduo/anaconda3/envs/ins-seg-pytorch/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/duoduo/anaconda3/envs/ins-seg-pytorch/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/duoduo/anaconda3/envs/ins-seg-pytorch/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90a734f4d0>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by Wizaron** [comment]
Did you start "visdom server" (`python -m visdom.server`) in a separate terminal before running "train.py"?

**Comment by zhengduoru** [comment]
哇塞成功了，虽然我没看懂这个visdom server～
Thank you so much!
