### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by zhengduoru** [Wizaron/instance-segmentation-pytorch#6]
when I ran dataset.py in code/lib

the code
 `if __name__ == '__main__':
    ds = SegDataset('../../../data/processed/lmdb/training-lmdb/')
    image, image_rgb, annotation, box_annotation, box_coordinate, \
n_objects = ds[5]`
seamed to be something wrong.

I saw the Class SegDataset only return 'img, annotation, n_objects',  but the code need six ?

I got the error 

  File "/home/duoduo/github/instance-segmentation-pytorch/code/lib/dataset.py", line 256, in <module>
    n_objects = ds[5]

ValueError: need more than 3 values to unpack

**Comment by Wizaron** [comment]
I updated main part of lib/dataset.py.

Thanks!
